### ISSUE TITLE
This failure might be due to the use of legacy binary "node"

### ISSUE THREAD

**Issue by aloisdg** [base16-builder/base16-builder#144]
## Steps to reproduce 

    npm test

## Expected Behaviour

see test output

## Actual Behaviour

> base16-builder@1.3.0 pretest /mnt/c/Users/alois/Source/Repos/base16-builder
> npm run build

> base16-builder@1.3.0 prebuild /mnt/c/Users/alois/Source/Repos/base16-builder
> rm -rf dist && mkdir dist && cp -R db/ dist/db

> base16-builder@1.3.0 build /mnt/c/Users/alois/Source/Repos/base16-builder
> node util/schemesPreviewGenerator.js && babel lib --out-dir dist && chmod +x dist/cli.js

```
sh: 1: node: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

## Node and npm versions

node v.0.10.25
npm 1.3.10

**Comment by aloisdg** [comment]
I tried this : [Cannot install packages using node package manager in Ubuntu](http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu/21171188#21171188). The error change a bit:

aloisdg@DESKTOP-QB7FE65:/mnt/c/Users/alois/Source/Repos/base16-builder$ npm test

> base16-builder@1.3.0 pretest /mnt/c/Users/alois/Source/Repos/base16-builder
> npm run build


> base16-builder@1.3.0 prebuild /mnt/c/Users/alois/Source/Repos/base16-builder
> rm -rf dist && mkdir dist && cp -R db/ dist/db


> base16-builder@1.3.0 build /mnt/c/Users/alois/Source/Repos/base16-builder
> node util/schemesPreviewGenerator.js && babel lib --out-dir dist && chmod +x dist/cli.js


/mnt/c/Users/alois/Source/Repos/base16-builder/util/schemesPreviewGenerator.js:17
      yamlSchemes = yamlSchemes.map(yamlScheme => yaml.load(yamlScheme))
                                                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by CrashyBang** [comment]
Hey @aloisdg can you try adding the `--harmony` flag?
